logging:
    level:
        root: ENC[AES256_GCM,data:90JY4w==,iv:ZpVF6UegnSCn73wmvQpMLot6/BmOGkqwg20T0jgUXak=,tag:o+Nc5p1gsmbSQ/tXvFbumg==,type:str]
        org.springframework:
            web: ENC[AES256_GCM,data:aqtj6NM=,iv:3c63NvtdeXcAxhLJ4rve0X31zt/djuDpvmKTFiFB4h0=,tag:QdwWQwDzUNA1bOFIwOHRbw==,type:str]
            security: ENC[AES256_GCM,data:E7KlFBM=,iv:hqbJT/Kyc0mYUE/x3fgrVM6usJOrGLYzRblBldnhY7I=,tag:AG19cQBJ1TVPSeEtCru47A==,type:str]
        reactor.netty.http.client: ENC[AES256_GCM,data:F6DYYJY=,iv:iGWHSJqrclIUH9n5n6YhfKvxbF76LiLidQBDr6uW52s=,tag:I/3ZQYKqauPep/vsjoYYYg==,type:str]
        org.running_credit: ENC[AES256_GCM,data:QbQzrdE=,iv:10qBjcvc3cDhrW3BP0fYx/fXwahfmnUvnAh1PhG7ZXc=,tag:R9ukBDaC9Z2Vm619W1lBsA==,type:str]
spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ENC[AES256_GCM,data:To6VK7JPNqeTkl5udjns+jM6+f2ICOOXAnVKeSqCSfcnnf5bZoI8mOVBmaeN5GnoLL2dEOZ8X0WSdnV6NcOCPhSamHT8uCpt,iv:EV3kzBpn2QO7e808zYEzoA9nRWVWncfhI1SzUsS5COg=,tag:EbO6Bfxak/DGjj6+jh34CA==,type:str]
                        client-secret: ENC[AES256_GCM,data:+JIj6L/yGfe3Uy7C5z+bqedrZCd4aW+v5NjINuw/035yXJE=,iv:hnA908FoWMW7lvojoMn0tyXLoSEo+gxbTMoneKLIAEY=,tag:1WigiUwOn7vUo4JbK3GJAw==,type:str]
                        authorization-grant-type: ENC[AES256_GCM,data:u223doy0qJJAzReJlHvSTL0t,iv:bbTuaS16bBjl0DqT7GIrz1HKaGvD1792qE5bqzhVLlg=,tag:K7ZN/J7yyBhEkdhGH240QQ==,type:str]
                        scope: ENC[AES256_GCM,data:ZsPedNv8jomBpqi87K+EZqStWugo8waiHpXklouq6ls0Ob7/gLc2EyM2HUEL92THC0vfPHE6RPM74SvFWbsIQvfOR0h5Ef7WpaBBgvV7jJkLhAIpQAwS5ZhIYaLipjN/Oq3S0XQ0smyMxXUcAfEBxcdnZsgfmZoEos8eSH/HP8U=,iv:0MNNDFizRetY4sKP3/l7EVEC4558eCTJp0l1KDwzIsI=,tag:K/X+dndDI+8GY9EkWqb7HA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e625734tkl6e2rteylqhkpzl74j9gqwxx0pfpj32f26dehpa5y6ssuzdcl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdW8za01SNmtzcDBDVXZ5
            SFh3Vng2U05NQnUxcEVHVHpoYUQvRThWUndVCm1QaGp2Q0dxSXFNc3dia3lBYjEy
            bUJkN1FTNWxwQmJQYWo0L0dHUm5ZeEEKLS0tIE9PTVJVUndrZENuaGprek9VNDN0
            UE9TZ1BLbGJNUXh0VnBtM0grSGpCZWMKX+3PekqcS3H5K44bD3mIHQFD/IVEo+5L
            UQmIabKKa2JUhXA1UXyA9QrGG5cVoibU2Vmm73DWUEtk5IEjW6sNbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T00:09:24Z"
    mac: ENC[AES256_GCM,data:97nEjrR4moIN7TfbR4fW5rxOzOlWsbXUf+sxRBUnBnxsJyqBjSH0bybtiUYqGSva+a6MpNR5vf6AChlWSiuyzvjO2+3Z8ywGljLsmNsZzcvHo7UzCpTryk9eWwtBPqMqXXyY2V0fn5WFbiIQV54NmOwbIK97GycSeGw2oiCrnU4=,iv:c88mrAJT2fjqhAH4THgFoYoEuXsd+wYOZRa6wDhHnew=,tag:bwFfeDviA/OKKuDYh5w+Mg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
